---
- name: "Install unattended-upgrades"
  ansible.builtin.apt:
    pkg: "unattended-upgrades"
    state: "present"

# ref. https://wiki.debian.org/PeriodicUpdates
- name: Create apt file that would be made by interactive dpkg-reconfigure
  ansible.builtin.copy:
    src: /usr/share/unattended-upgrades/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    remote_src: true
    owner: root
    group: root
    mode: '0644'

# https://wiki.debian.org/PeriodicUpdates?action=show&redirect=UnattendedUpgrades#Configure_unattended-upgrades
- name: Create override config file
  ansible.builtin.copy:
    src: /usr/share/unattended-upgrades/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
    remote_src: true
    owner: root
    group: root
    mode: '0644'

# ref. https://help.ubuntu.com/community/Lubuntu/Documentation/RemoveOldKernels#Shell
- name: Enable remove unused deps
  ansible.builtin.lineinfile:
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
    line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
    insertafter: '^//Unattended-Upgrade::Remove-Unused-Dependencies'
